# Aletheia Fractal Analysis Configuration

# Data paths
data:
  base_path: '/home/echo/Desktop/Taylor_Lab/AletheiaRunData/'
  interpolated_file: 'interpdata.csv'
  raw_file: 'rotatedata.csv'  # raw data file name
  # Data file to use for batch mode discovery and interpolation source
  data_file: 'interpdata.csv'  # 'interpdata.csv' or 'rotatedata.csv'

# Single dataset processing settings
single:
  person: 'P049'
  speed: '05-0mph'
  run_id: '1737'

# Batch processing settings
batch:
  enabled: false  # Set to true to process multiple datasets from data_to_run.csv
  output_base_dir: 'batch_test_082925'  # Base directory for all batch outputs (plots, logs, results)

# Interpolation settings
interpolation:
  enabled: true  # Set to false to use pre-interpolated data
  factor: 100  # How many times to increase resolution
  method: 'cubic_spline'  # 'cubic_spline' or 'linear'
  save_interpolated: true  # Save interpolated data to file with "_interpolated" suffix

# Analysis parameters
analysis:
  min_box_divisions: 5
  max_box_divisions_factor: 2.0  # Multiplier for max divisions calculation
  num_box_scales: 15  # Number of box counting scales to test
  min_fit_points: 4  # Minimum points for linear regression fit
  
  # Fractal dimension calculation method
  use_sliding_grid: false  # Set to true for sliding grid method (more accurate but slower)
  grid_shifts: 5  # Number of grid shifts to try in sliding grid method (higher = more accurate but slower)

# Visualization settings
visualization:
  figure_size: [12, 8]  # Increased width for 3D plots
  dpi: 300
  save_format: 'png'
  plot_3d_trajectory: true  # Set to true to include 3D trajectory plot
  interactive_3d: false       # Set to true for interactive 3D plot (requires plotly)
  density_coloring: false     # Set to true for density-based color coding in 3D plots
  # 3D plot specific settings
  scatter_alpha: 0.1        # Transparency of scatter points
  scatter_size: 0.05        # Size of scatter points
  line_width: 0.2           # Width of trajectory line
  colormap: 'plasma'        # Colormap for density coloring

# Logging
logging:
  level: 'INFO' # INFO, DEBUG, WARNING, ERROR
  include_console: true # Set to true to show console output
  include_file: true # Set to true to output to a file